"""third-add_like_count

Revision ID: fb14baa361c1
Revises: 46e518bfbcd2
Create Date: 2025-03-10 12:16:32.159246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb14baa361c1'
down_revision: Union[str, None] = '46e518bfbcd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'like_count')
    # ### end Alembic commands ###
